source "https://rubygems.org"
gemspec

gem "rails", "~> 8.0.0"
gem "selenium-webdriver"
gem "props_template", path: "../props_template"
gem "humid", path: "../humid"
gem "standard"
gem "capybara"
gem "minitest", "~> 5.27"
gem "minitest-mock"
gem "rake"
gem "sqlite3"
gem "git", "~> 4.3"
gem "jsbundling-rails"
gem "puma"
gem "propshaft"
gem "redis"
gem "cuprite"
gem "dotenv"
