source "https://rubygems.org"
gemspec

gem "rails", "~> 7.2.0"
gem "selenium-webdriver"
gem "props_template", path: "../props_template"
gem "standard"
gem "capybara"
gem "minitest"
gem "rake"
gem "sqlite3", "~> 1.4"
gem "byebug"
gem "git"
gem "jsbundling-rails"
gem "puma"
gem "propshaft"
gem "redis"
gem "cuprite"
